# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-17 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_change_meta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidcourseregistration',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
